(function(g){var window=this;'use strict';var sf=function(Q){Q.publish("cardstatechange",Q.ME()&&Q.TR()?1:0)},dX=function(Q,c){var W=g.iw(c);
const m=W?c:arguments;for(W=W?0:1;W<m.length;W++){if(Q==null)return;Q=Q[m[W]]}return Q},YZS=function(Q){const c=g.Tk(Q);
Q=g.A4(Q);return new g.zC(c.x,c.y,Q.width,Q.height)},pBD=function(Q,c,W){let m;
return m=g.ph(Q,c,function(){g.Qg(m);W.apply(Q,arguments)},{})},bW=function(Q){Q=g.ZR(Q);
delete L_[Q];g.P9(L_)&&wX&&wX.stop()},c44=function(){wX||(wX=new g.Uc(function(){QaD()},20));
const Q=wX;Q.isActive()||Q.start()},QaD=function(){var Q=g.d0();
g.ZS(L_,function(c){Wlm(c,Q)});
g.P9(L_)||c44()},jR=function(Q,c,W,m){g.H7.call(this);
if(!Array.isArray(Q)||!Array.isArray(c))throw Error("Start and end parameters must be arrays");if(Q.length!=c.length)throw Error("Start and end points must be the same length");this.O=Q;this.J=c;this.duration=W;this.K=m;this.coords=[];this.progress=this.D=0;this.j=null},Wlm=function(Q,c){c<Q.startTime&&(Q.endTime=c+Q.endTime-Q.startTime,Q.startTime=c);
Q.progress=(c-Q.startTime)/(Q.endTime-Q.startTime);Q.progress>1&&(Q.progress=1);Q.D=1E3/(c-Q.j);Q.j=c;mfa(Q,Q.progress);Q.progress==1?(Q.W=0,bW(Q),Q.onFinish(),Q.KA()):Q.isPlaying()&&Q.Nw()},mfa=function(Q,c){typeof Q.K==="function"&&(c=Q.K(c));
Q.coords=Array(Q.O.length);for(let W=0;W<Q.O.length;W++)Q.coords[W]=(Q.J[W]-Q.O[W])*c+Q.O[W]},KlH=function(Q,c){g.tG.call(this,Q);
this.coords=c.coords;this.x=c.coords[0];this.y=c.coords[1];this.z=c.coords[2];this.duration=c.duration;this.progress=c.progress;this.fps=c.D;this.state=c.W},gX=function(Q,c,W,m,K){jR.call(this,c,W,m,K);
this.element=Q},Of=function(Q,c,W,m,K){if(c.length!=2||W.length!=2)throw Error("Start and end points must be 2D");
gX.call(this,Q,c,W,m,K)},Tf0=function(Q){return Math.pow(Q,3)},oyi=function(Q){return 3*Q*Q-2*Q*Q*Q},f_=function(Q){return Q.baseUrl||null},vM=function(Q,c){return g.uw(g.hy(Q,c),W=>!!W)},r4W=function(Q,c,W){function m(yn){var $x=yn.hovercardButton;
if(!$x)return null;$x=$x.subscribeButtonRenderer;if(!$x)return null;const z7=T($x.unsubscribedButtonText),wT=T($x.subscribedButtonText);let P3,Ft;$x.subscribed?(P3=T($x.subscriberCountWithUnsubscribeText),Ft=T($x.subscriberCountText)):(P3=T($x.subscriberCountText),Ft=T($x.subscriberCountWithSubscribeText));let CR=null;return yn.signinEndpoint&&((CR=dX(yn,"signinEndpoint","webNavigationEndpointData","url"))||(CR=g.l($x.signInEndpoint?.commandMetadata,g.bu)?.url),!CR)?null:z7&&(wT||CR)?{subscribed:$x.subscribed,
subscribeText:z7,subscribeCount:P3,unsubscribeText:wT,unsubscribeCount:Ft,enabled:$x.enabled,signinUrl:CR,classic:yn.useClassicSubscribeButton}:null}
function K(yn){if(yn){var $x=[],z7=yn.videoId;z7&&$x.push("v="+z7);(z7=yn.playlistId)&&$x.push("list="+z7);(yn=yn.startTimeSeconds)&&$x.push("t="+yn);return"/watch?"+$x.join("&")}}
function T(yn){if(!yn)return null;const $x=yn.simpleText;return $x?$x:yn.runs?g.hy(yn.runs,z7=>z7.text).join(""):null}
c=c.endscreenElementRenderer;if(!c)return null;const r=c.style,U=c.endpoint||{};let I=null;var X=null,A=!1;let e=null,V=null,B=null,n=null;var S=!1;let d=null,b=null;var w=null;let f=null,G=null,T7=null;if(r==="VIDEO")g.l(U,g.s8)?I=g.l(U,g.s8).url:(T7=g.l(U,g.nl),I=K(T7)),X=!1,e=Q,c.thumbnailOverlays?(A=c.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,V=T(A.text),A=A.style==="LIVE"):V=T(c.videoDuration);else if(r==="PLAYLIST")g.l(U,g.s8)?I=g.l(U,g.s8).url:(T7=g.l(U,g.nl),I=K(T7)),X=!1,e=
Q,B=T(c.playlistLength);else if(r==="CHANNEL"){if(S=dX(U,"browseEndpoint","browseId"))n=S,I=`/channel/${n}`;X=!1;e="new";(S=!!c.isSubscribe)?d=m(c):b=T(c.subscribersText)}else r==="WEBSITE"?((w=dX(U,"urlEndpoint","url"))&&(I=w),X=!0,e="new",w=c.icon.thumbnails[0].url):r==="CREATOR_MERCHANDISE"&&(c.productPrice&&(f=T(c.productPrice)),c.additionalFeesText&&(G=T(c.additionalFeesText)),(X=dX(U,"urlEndpoint","url"))&&(I=X),X=!0,e="new");Q=dX(c,"title","accessibility","accessibilityData","label");const oW=
c.endpoint?c.endpoint.clickTrackingParams:null;let G7="";if(c.metadata){const yn=T(c.metadata);yn&&(G7=yn)}return{id:`element-${W}`,type:r,title:T(c.title),metadata:G7,callToAction:T(c.callToAction),eq:c.image,iconUrl:w,left:Number(c.left),width:Number(c.width),top:Number(c.top),aspectRatio:Number(c.aspectRatio),startMs:Math.floor(Number(c.startMs)),endMs:Math.floor(Number(c.endMs)),videoDuration:V,d8:A,playlistLength:B,channelId:n,subscribeButton:d,subscribersText:b,isSubscribe:S,targetUrl:I||null,
D4:X,sessionData:oW?{itct:oW}:null,un:e,Vu:Q?Q:null,isPlaceholder:c.isPlaceholder,impressionUrls:vM(c.impressionUrls||[],f_),zz:vM(c.hovercardShowUrls||[],f_),clickUrls:vM(U.loggingUrls||[],f_),visualElement:g.Bo(c.trackingParams),productPrice:f,additionalFeesText:G,watchEndpoint:T7||null}},ay=function(Q,c){const W={startMs:Math.floor(Number(Q.startMs)),
impressionUrls:vM(Q.impressionUrls||[],f_),elements:vM(Q.elements||[],(m,K)=>r4W(c,m,K))};
Q.trackingParams&&(W.visualElement=g.Bo(Q.trackingParams));return W},G4=function(Q){return Q.player.G().playerStyle==="creator-endscreen-editor"},Uf9=function(Q){return Q.player.getVideoData().er?"current":Q.Y?"new":"current"},$P=function(Q,c,W=!0){Q.player.qI("creatorendscreen");
Q.A&&(Q.A.dispose(),Q.A=null,Q.K.dispose(),Q.K=null);for(var m of Object.values(Q.O))m.dispose();Q.O={};Q.D={};Q.L.length>0&&(Q.L.forEach(K=>{K.dispose()}),Q.L.length=0);
Q.W&&(g.n6(Q.W,"ytp-ce-element-show"),Q.W.setAttribute("aria-hidden","true"));Q.J=0;if((Q.endscreen=c)&&c.elements){W&&IOv(Q);W=[];m=new g.C8(c.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});W.push(m);Q.player.G().O||(Q.A=new g.k({C:"div",Z:"ytp-ce-shadow"}),g.f8(Q.player,Q.A.element,4),Q.K=new g.QR(Q.A,200));for(m=0;m<c.elements.length;++m){const K=c.elements[m],T=XSi(Q,K);if(!T){g.Ty(new g.H8("buildEndscreenElement null",K));continue}Q.O[K.id]=T;Q.D[K.id]=K;g.f8(Q.player,
T.element,4);const r=new g.C8(K.startMs,K.endMs,{id:"ytp-ce-element-"+K.id,namespace:"creatorendscreen"});W.push(r);A4D(Q,T,K)}Q.player.mV(W);Q.b3()}},eLi=function(Q){var c=Q.player.getVideoData(),W=c.videoId;
Q.j&&Q.j.abort();W={method:"POST",onFinish:K=>{var T=Q.j=null;K.status===200&&(K=K.responseText,K.substring(0,3)===")]}"&&(K=K.substring(3),T=JSON.parse(K),T=ay(T,Uf9(Q))));$P(Q,T)},
urlParams:{v:W},withCredentials:!0};Q.Y&&(W.urlParams.ptype="embedded");const m=c.Vd;m&&(W.postParams={ad_tracking:m});if(c=g.IFO(c))if(c=g.k9(c),c=g.C9(c))Q.j=g.Wn(c,W)},IOv=function(Q){const c=g.na(),W=g.Df();
W&&c&&Q.endscreen.visualElement&&g.Ei(g.Po)(void 0,W,c,Q.endscreen.visualElement)},XSi=function(Q,c){var W=null;
switch(c.type){case "VIDEO":Q={C:"div",yC:["ytp-ce-element","ytp-ce-video"],N:{tabindex:"0","aria-label":c.Vu||"","aria-hidden":"true"},V:[{C:"div",Z:"ytp-ce-element-shadow"},{C:"div",Z:"ytp-ce-covering-image",N:PM(c)},{C:"div",Z:"ytp-ce-covering-shadow-top"},{C:"a",Z:"ytp-ce-covering-overlay",N:{href:lW(Q,c.targetUrl),tabindex:"-1"},V:[{C:"div",yC:["ytp-ce-video-title","ytp-webkit-ellipsis"],N:{dir:g.sc(c.title||"")},eG:c.title},{C:"div",Z:c.d8?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
eG:c.videoDuration||void 0}]}]};W=new g.k(Q);break;case "PLAYLIST":Q={C:"div",yC:["ytp-ce-element","ytp-ce-playlist"],N:{tabindex:"0","aria-label":c.Vu||"","aria-hidden":"true"},V:[{C:"div",Z:"ytp-ce-element-shadow"},{C:"div",Z:"ytp-ce-covering-image",N:PM(c)},{C:"div",Z:"ytp-ce-covering-shadow-top"},{C:"a",Z:"ytp-ce-covering-overlay",N:{href:lW(Q,c.targetUrl),tabindex:"-1"},V:[{C:"div",yC:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],N:{dir:g.sc(c.title||"")},eG:c.title},{C:"div",Z:"ytp-ce-playlist-count",
V:[{C:"div",Z:"ytp-ce-playlist-icon"},{C:"div",Z:"ytp-ce-playlist-count-text",eG:c.playlistLength||void 0}]}]}]};W=new g.k(Q);break;case "CHANNEL":W={C:"div",yC:["ytp-ce-element","ytp-ce-channel",c.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],N:{tabindex:"0","aria-label":c.Vu||"","aria-hidden":"true"},V:[{C:"div",Z:"ytp-ce-element-shadow"},{C:"div",Z:"ytp-ce-expanding-overlay",V:[{C:"div",Z:"ytp-ce-expanding-overlay-hider"},{C:"div",Z:"ytp-ce-expanding-overlay-background"},{C:"div",Z:"ytp-ce-expanding-overlay-content",
V:[{C:"div",Z:"ytp-ce-expanding-overlay-body",V:[{C:"div",Z:"ytp-ce-expanding-overlay-body-padding",V:[{C:"a",yC:["ytp-ce-channel-title","ytp-ce-link"],N:{href:lW(Q,c.targetUrl),target:"_blank",tabindex:"-1",dir:g.sc(c.title||"")},eG:c.title},c.subscribeButton?{C:"div",Z:"ytp-ce-subscribe-container",V:[{C:"div",Z:"ytp-ce-channel-subscribe"}]}:"",c.subscribersText?{C:"div",Z:"ytp-ce-channel-subscribers-text",eG:c.subscribersText}:"",c.metadata?{C:"div",yC:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],eG:c.metadata}:""]}]}]}]},{C:"div",Z:"ytp-ce-expanding-image",N:PM(c)}]};W=new g.k(W);const K=g.UZ(document,"div","ytp-ce-channel-subscribe",W.element)[0];if(c.subscribeButton&&c.channelId){g.xK(K,"ytp-ce-subscribe-button");let T;if(Q.player.G().O){var m=null;T=c.sessionData.itct}else m="endscreen",T=null;m=new g.tW(c.subscribeButton.subscribeText,c.subscribeButton.subscribeCount,c.subscribeButton.unsubscribeText,c.subscribeButton.unsubscribeCount,!!c.subscribeButton.enabled,!!c.subscribeButton.classic,
c.channelId,!!c.subscribeButton.subscribed,m,T,Q.player,!1);K.appendChild(m.element);Q.L.push(m)}break;case "WEBSITE":Q={C:"div",yC:["ytp-ce-element","ytp-ce-website"],N:{tabindex:"0","aria-label":c.Vu||"","aria-hidden":"true"},V:[{C:"div",Z:"ytp-ce-element-shadow"},{C:"div",Z:"ytp-ce-expanding-overlay",V:[{C:"div",Z:"ytp-ce-expanding-overlay-hider"},{C:"div",Z:"ytp-ce-expanding-overlay-background"},{C:"div",Z:"ytp-ce-expanding-overlay-content",V:[{C:"div",Z:"ytp-ce-expanding-overlay-body",V:[{C:"div",
Z:"ytp-ce-expanding-overlay-body-padding",V:[{C:"div",Z:"ytp-ce-website-title",N:{dir:g.sc(c.title||"")},eG:c.title},{C:"div",Z:"ytp-ce-website-metadata",eG:c.metadata},{C:"a",yC:["ytp-ce-website-goto","ytp-ce-link"],N:{href:lW(Q,c.targetUrl),target:"_blank",tabindex:"-1"},eG:c.callToAction}]}]}]}]},{C:"div",Z:"ytp-ce-expanding-image",N:PM(c)},{C:"div",Z:"ytp-ce-expanding-icon",N:Vev(c.iconUrl)}]};W=new g.k(Q);break;case "CREATOR_MERCHANDISE":W="",c.productPrice&&(W={C:"div",Z:"ytp-ce-merchandise-price-container",
V:[{C:"div",Z:"ytp-ce-merchandise-price",eG:c.productPrice}]},c.additionalFeesText&&W.V.push({C:"div",Z:"ytp-ce-merchandise-additional-fees",eG:c.additionalFeesText})),Q={C:"div",yC:["ytp-ce-element","ytp-ce-merchandise"],N:{tabindex:"0","aria-label":c.Vu||"","aria-hidden":"true"},V:[{C:"div",Z:"ytp-ce-element-shadow"},{C:"div",Z:"ytp-ce-expanding-overlay",V:[{C:"div",Z:"ytp-ce-expanding-overlay-hider"},{C:"div",Z:"ytp-ce-expanding-overlay-background"},{C:"div",Z:"ytp-ce-expanding-overlay-content",
V:[{C:"div",Z:"ytp-ce-expanding-overlay-body",V:[{C:"div",Z:"ytp-ce-expanding-overlay-body-padding",V:[{C:"div",Z:"ytp-ce-merchandise-title",N:{dir:g.sc(c.title||"")},eG:c.title},W,{C:"div",Z:"ytp-ce-merchandise-metadata",eG:c.metadata},{C:"a",yC:["ytp-ce-merchandise-goto","ytp-ce-link"],N:{href:lW(Q,c.targetUrl),target:"_blank",tabindex:"-1"},eG:c.callToAction}]}]}]}]},{C:"div",Z:"ytp-ce-expanding-image",N:PM(c)},{C:"div",Z:"ytp-ce-merchandise-invideo-cta-container",V:[{C:"div",Z:"ytp-ce-merchandise-invideo-cta",
eG:c.callToAction||void 0}]}]},W=new g.k(Q)}c.isPlaceholder&&g.xK(W.element,"ytp-ce-placeholder");return W},A4D=function(Q,c,W){function m(){r(1)}
function K(){r(-1)}
c.listen("mouseenter",()=>{uW(Q,c,W)});
c.listen("mouseleave",()=>{h2(Q,c,W)});
Q.player.G().O||c.listen("click",()=>{g.xK(c.element,"ytp-ce-element-hover")});
c.listen("click",U=>{BfW(Q,W,U)});
c.listen("keypress",U=>{BfW(Q,W,U)});
c.listen("focus",()=>{uW(Q,c,W)});
c.listen("blur",()=>{h2(Q,c,W)});
c.listen("touchstart",()=>{uW(Q,c,W)});
var T=g.I_("ytp-ce-expanding-overlay-hider",c.element);T&&c.B(T,"touchstart",U=>{U.stopPropagation();g.n6(c.element,"ytp-ce-element-hover");g.n6(c.element,"ytp-ce-force-expand")});
c.listen("keydown",U=>{Q.mF=U.keyCode===9&&!U.shiftKey});
const r=U=>{Q.J+=U;Q.J>0?(g.xK(c.element,"ytp-ce-force-expand"),z4(Q,W.id,!0)):(g.n6(c.element,"ytp-ce-force-expand"),g.n6(c.element,"ytp-ce-element-hover"),z4(Q,W.id,!1))};
T=U=>{U&&(c.listen("blur",()=>{U.style.display!="none"&&Q.mF&&U.focus()}),c.B(U,"focus",m),c.B(U,"blur",K))};
T(g.I_("ytp-sb-subscribe",c.element));T(g.I_("ytp-sb-unsubscribe",c.element));c.listen("focus",m);c.listen("blur",K)},C_=function(Q,c,W){function m(){T||(K++,K===c.length&&(r.stop(),W&&W()))}
if(!c||c.length===0||G4(Q))W&&W();else{c=xfa(Q,c);var K=0,T=!1,r=new g.Uc(()=>{T=!0;W&&W()},1E3,Q);
r.start();for(Q=0;Q<c.length;Q++)g.GU(c[Q],m)}},PM=function(Q){let c;
Q.eq&&(c=Q.eq.thumbnails);return Vev(c?c[c.length-1].url:null)},lW=function(Q,c){Q=Q.player.G();
if(c){if(c.startsWith("//"))return Q.protocol+":"+c;if(c.startsWith("/"))return g.jh(Q)+c}else return"";return c},Vev=function(Q){return Q?{style:"background-image: url("+Q+")"}:{}},uW=function(Q,c,W){g.B7(c.element,"ytp-ce-element-hover")||(W.type==="VIDEO"||W.type==="PLAYLIST"?g.xK(c.element,"ytp-ce-element-hover"):Q.player.G().O?(new g.Uc(()=>{g.xK(c.element,"ytp-ce-element-hover")},200)).start():g.xK(c.element,"ytp-ce-element-hover"),C_(Q,W.zz),z4(Q,W.id,!0))},h2=function(Q,c,W){g.n6(c.element,
"ytp-ce-element-hover");
g.n6(c.element,"ytp-ce-force-expand");z4(Q,W.id,!1)},BfW=function(Q,c,W){if(c.targetUrl&&(!W||W.type!=="keypress"||W.keyCode===13)){for(var m=W.target;m&&!g.B7(m,"ytp-ce-element");){g.B7(m,"subscribe-label")&&Mo(Q,c);
if(g.B7(m,"ytp-ce-channel-subscribe"))return;m=m.parentElement||null}if(!m||g.B7(m,"ytp-ce-element-hover")){W.preventDefault();W.stopPropagation();if(m=Q.O[c.id])h2(Q,m,c),m.element.blur();if(W.ctrlKey||W.metaKey||c.un==="new")Mo(Q,c),Q.player.sendVideoStatsEngageEvent(17,void 0),Q.player.pauseVideo(),W=g.k9(lW(Q,c.targetUrl)),W=g.C9(W),g.Fw(W,void 0,c.sessionData);else{const K=g.rT(Q.player.G())||Q.player.getVideoData().er,T=()=>{var r=lW(Q,c.targetUrl),U=c.sessionData,I=c.watchEndpoint;const X=
g.g_(r);K&&X&&(X.v||X.list)?Q.player.SF(X.v,U,X.list,!1,void 0,I||void 0):g.SE(r,U)};
Mo(Q,c,()=>{Q.player.sendVideoStatsEngageEvent(17,T)})}}}},z4=function(Q,c,W){Q.A&&(W?Q.K.show():Q.K.hide());
for(const m of Object.keys(Q.O))m!==c&&g.L(Q.O[m].element,"ytp-ce-element-shadow-show",W)},Mo=function(Q,c,W){C_(Q,c.clickUrls,W);
(Q=g.Df())&&c.D4&&g.pa(Q,c.visualElement)},xfa=function(Q,c){var W=Q.player.getVideoData().clientPlaybackNonce;
Q=Q.player.getCurrentTime().toFixed(2);W={CPN:W,AD_CPN:W,MT:Q};Q=[];for(let m=0;m<c.length;m++)Q.push(qTa(c[m],W));return Q},qTa=function(Q,c){return Q.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,W=>{let m=unescape(W);
m=m.substring(1,m.length-1);return c[m]?escape(c[m]):W})},nyv=function(Q){return typeof Q==="string"?Q:""},J2=function(Q,c,W){for(const m in c)if(c[m]===Q)return Q;
return W},Ry=function(Q){if(!Q)return null;
var c=g.k9(nyv(Q.value));c=g.C9(c);if(!c)return null;const W=J2(Q.target,Dfa,"current");if(W==null)Q=null;else{var m=Q.show_link_icon;Q=new te9(c,W,m==="true"||m==="false"?m==="true":!0,Q.pause_on_navigation!=null?Q.pause_on_navigation:!0)}return Q},y4W=function(Q){if(!Q)return null;
const c=J2(Q.type,HN9),W=J2(Q.trigger,NfH);Q=Q.url;Q=Array.isArray(Q)&&Q.length?Q[0]:Q;Q=Ry(Q?Q:null);return c?new iND(c,W,Q):null},STZ=function(Q,c){return g.Yx(Q.action,c)},kP=function(Q,c){Q="background-image: url("+Q+");";
const W=[];c&&W.push(c);return{C:"div",Z:"iv-card-image",N:{style:Q},V:W}},p_=function(Q){return Q.customMessage?YP("div","iv-card-message",Q.customMessage):""},QX=function(Q){if(!Q.metaInfo||Q.metaInfo.length===0)return"";
const c=[];for(const W of Q.metaInfo)c.push(YP("li","",W));return{C:"ul",Z:"iv-card-meta-info",V:c}},cA=function(Q,c,W,m){if(m)for(const K of c)Q.W(K,m,W.id,W.sessionData,W.C2.click,5)},YP=function(Q,c,W){c?typeof c==="string"?c={"class":c}:Array.isArray(c)&&(c={"class":c.join(" ")}):c={};
c.dir=g.sc(W);return{C:Q,N:c,eG:W}},FlD=function(Q){if(!Q.customMessage)return"";
const c=["iv-card-action","iv-card-primary-link"],W={};Q.WC&&(c.push("iv-card-action-icon"),W.style="background-image: url("+Q.WC+");");W.dir=g.sc(Q.customMessage);const m=[{C:"span",eG:Q.customMessage}];Q.showLinkIcon&&(m.push("\u00a0"),m.push({C:"span",Z:"iv-card-link-icon"}));return{C:"div",yC:c,N:W,V:m}},ZN4=function(Q){var c;
(c=Q)&&!(c=Q.length>1?Q.charAt(0)==="/"&&Q.charAt(1)!=="/":Q==="/")&&(c=Q.replace(/^(https?:)?\/\//,"").split("/",1),c=!c||c.length<1||!c[0]?[]:c[0].toLowerCase().split(".").reverse(),c=c[0]==="com"&&c[1]==="youtube"||c[0]==="be"&&c[1]==="youtu");return c?Q.indexOf("/redirect?")===-1:!1},EyW=function(Q,c){return c?c:ZN4(Q)?"current":"new"},WA=function(Q,c,W,m,K,T,r){Q.context.W.listen(c,"click",U=>{Q.HA(W,m,K,T||[],r||0,U)});
Q.context.W.listen(c,"touchstart",()=>{Q.EC=!1});
Q.context.W.listen(c,"touchmove",()=>{Q.EC=!0})},saH=function(Q){if(g.l(Q,g.s8)?.url)return g.l(Q,g.s8).url;
if((Q=g.l(Q,g.nl))&&Q.videoId){let c="/watch?v="+Q.videoId;Q.playlistId&&(c+="&list="+Q.playlistId);Q.index&&(c+="&index="+Q.index);Q.startTimeSeconds&&(c+="&t="+Q.startTimeSeconds);return c}return null},mP=function(Q,c,W){return{KJ:(Q.impressionLoggingUrlsV2s||[]).map(m=>m.baseUrl||""),
click:(W.loggingUrls||[]).map(m=>m.baseUrl||""),
close:(c.dismissLoggingUrlsV2s||[]).map(m=>m.baseUrl||""),
CE:(c.impressionLoggingUrlsV2s||[]).map(m=>m.baseUrl||""),
F$:(c.clickLoggingUrlsV2s||[]).map(m=>m.baseUrl||"")}},rE=function(Q,c){if(c.onClickCommand&&g.l(c.onClickCommand,g.yuy)?.targetId==="engagement-panel-error-corrections"){Q.S=c;
var W=!0}else W=!1;if(!W||dfW(Q,c))if(W=LlW(Q,c)){var m={XO:c,D9:W.element,fR:!1};if(c.onClickCommand)Q.U.X("web_infocards_teaser_show_logging_fix")&&(Q.iX||bN4(Q),Ky(Q,c.id),W=Q.findLastIndex(m),g.q9(Q.cards,W,0,m));else{Q.isInitialized||wS4(Q);Ky(Q,c.id);const K=Q.findLastIndex(m);g.q9(Q.cards,K,0,m);W.x0(Q.O,K);Q.MM()}c.autoOpen?Q.addCueRange(c.startMs,0x8000000000000,c.id,()=>{Q.A||(Q.W=m,Tl(Q),jaS(Q,m),of(Q,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(W=Q.context.U.getCurrentTime()*1E3,W<5E3&&W>c.startMs&&
gyS(Q,m),Q.addCueRange(c.startMs,c.startMs+1,c.id,()=>{gyS(Q,m)}),Tl(Q))}},Ur=function(Q){Q.A&&(Q.Y0.hide(),Q.UH.O(),g.n6(Q.context.U.getRootNode(),g.qa.IV_DRAWER_OPEN),Q.A=!1,sf(Q.U),Q.D&&Q.D.stop(),Q.D=new g.Uc(()=>{Q.jG&&(Q.jG.focus(),Q.jG=null)},330),Q.D.start())},ON4=function(Q,c){c=c.data;
c.autoOpenMs&&Q.addCueRange(c.autoOpenMs,0x8000000000000,"",()=>{of(Q,"YOUTUBE_DRAWER_AUTO_OPEN")});
c.autoCloseMs&&Q.addCueRange(c.autoCloseMs,0x8000000000000,"",()=>{Ur(Q)});
const W=c.headerText;g.EZ(Q.WB,W);Q.K&&(Q.U.X("player_tooltip_data_title_killswitch")?Q.K.setAttribute("title",W):Q.K.setAttribute("data-tooltip-title",W));c.eventId&&(Q.eventId=c.eventId);Q.Ka=g.Bo(c.trackingParams);Q.L=g.Bo(c.closeTrackingParams);Q.Vj=g.Bo(c.iconTrackingParams)},If=function(Q,c,W){let m=-1,K=-1;
for(let T=0;T<Q.length;T++){if(Q[T].height===c||Q[T].width===W)return Q[T];((Q[T].height||0)<c||(Q[T].width||0)<W)&&(m<0||(Q[m].height||0)<(Q[T].height||0)||(Q[m].width||0)<(Q[T].width||0))?m=T:((Q[T].height||0)>=c||(Q[T].width||0)>=W)&&(K<0||(Q[K].height||0)>(Q[T].height||0)||(Q[K].width||0)>(Q[T].width||0))&&(K=T)}return Q[K>=0?K:m]},X8=function(Q,c,W,m){return{feature:W.feature?W.feature:"cards",
src_vid:Q.context.videoData.videoId,annotation_id:c,ei:Q.context.videoData.eventId||"",itct:m.trackingParams||""}},fOW=function(Q,c){const W=c.cardId?c.cardId:`cr:${Q.J}`;
var m=Q.U.G().experiments.SG("enable_error_corrections_infocard_web_client");if(!c.content&&c.teaser.simpleCardTeaserRenderer&&m){m=c.teaser.simpleCardTeaserRenderer;var K=c.icon?c.icon.infoCardIconRenderer:null;if(m.channelAvatar&&m.channelAvatar.thumbnails&&m.channelAvatar.thumbnails.length>0)var T=If(m.channelAvatar.thumbnails,22,22).url;c={id:W,timestamp:Q.J,type:"simple",teaserText:g.rK(m.message),teaserDurationMs:Number(c.cueRanges[0].teaserDurationMs),startMs:Number(c.cueRanges[0].startCardActiveMs),
autoOpen:!!c.autoOpen,sessionData:{},sponsored:!1,C2:{},Wp:null,eg:m.trackingParams?g.Bo(m.trackingParams):null,Vj:K&&K.trackingParams?g.Bo(K.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,WC:null,title:"",customMessage:"",url:null,onClickCommand:m.onTapCommand||null,nT:T};rE(Q,c)}else if(c.content?.simpleCardContentRenderer){if(!c.cueRanges.length)return;T=c.content?.simpleCardContentRenderer;m=c.teaser.simpleCardTeaserRenderer;K=c.icon?c.icon.infoCardIconRenderer:null;c={id:W,
timestamp:Q.J,type:"simple",teaserText:g.rK(m.message),teaserDurationMs:Number(c.cueRanges[0].teaserDurationMs),startMs:Number(c.cueRanges[0].startCardActiveMs),autoOpen:!!c.autoOpen,sessionData:X8(Q,W,c,T),sponsored:!1,C2:mP(T,m,T.command),Wp:T.trackingParams?g.Bo(T.trackingParams):null,eg:m.trackingParams?g.Bo(m.trackingParams):null,Vj:K&&K.trackingParams?g.Bo(K.trackingParams):null,imageUrl:If(T.image.thumbnails,290,290).url,displayDomain:T.displayDomain?g.rK(T.displayDomain):null,showLinkIcon:!!T.showLinkIcon,
WC:null,title:T.title?g.rK(T.title):"",customMessage:T.callToAction?g.rK(T.callToAction):"",url:g.l(T.command,g.s8).url?Ry({pause_on_navigation:!Q.context.videoData.isLivePlayback,target:"new",value:g.l(T.command,g.s8).url}):null,onClickCommand:null};rE(Q,c)}else if(c.content?.collaboratorInfoCardContentRenderer){if(!c.cueRanges.length)return;T=c.content?.collaboratorInfoCardContentRenderer;m=c.teaser.simpleCardTeaserRenderer;K=c.icon?c.icon.infoCardIconRenderer:null;c={id:W,timestamp:Q.J,type:"collaborator",
teaserText:g.rK(m.message),teaserDurationMs:Number(c.cueRanges[0].teaserDurationMs),startMs:Number(c.cueRanges[0].startCardActiveMs),autoOpen:!!c.autoOpen,sessionData:X8(Q,W,c,T),sponsored:!1,C2:mP(T,m,T.endpoint),Wp:T.trackingParams?g.Bo(T.trackingParams):null,eg:m.trackingParams?g.Bo(m.trackingParams):null,Vj:K&&K.trackingParams?g.Bo(K.trackingParams):null,channelId:g.l(T.endpoint,g.qR).browseId,customMessage:T.customText?g.rK(T.customText):null,profileImageUrl:If(T.channelAvatar.thumbnails,290,
290).url,title:T.channelName?g.rK(T.channelName):"",metaInfo:[T.subscriberCountText?g.rK(T.subscriberCountText):""],url:Ry({pause_on_navigation:!Q.context.videoData.isLivePlayback,target:"new",value:g.l(T.endpoint,g.qR).canonicalBaseUrl?g.l(T.endpoint,g.qR).canonicalBaseUrl:`/channel/${g.l(T.endpoint,g.qR).browseId}`}),onClickCommand:null};rE(Q,c)}else if(c.content?.playlistInfoCardContentRenderer){if(!c.cueRanges.length)return;T=c.content?.playlistInfoCardContentRenderer;m=c.teaser.simpleCardTeaserRenderer;
K=c.icon?c.icon.infoCardIconRenderer:null;c={id:W,timestamp:Q.J,type:"playlist",teaserText:g.rK(m.message),teaserDurationMs:Number(c.cueRanges[0].teaserDurationMs),startMs:Number(c.cueRanges[0].startCardActiveMs),autoOpen:!!c.autoOpen,sessionData:X8(Q,W,c,T),sponsored:!1,C2:mP(T,m,T.action),Wp:T.trackingParams?g.Bo(T.trackingParams):null,eg:m.trackingParams?g.Bo(m.trackingParams):null,Vj:K&&K.trackingParams?g.Bo(K.trackingParams):null,SV:If(T.playlistThumbnail.thumbnails,258,290).url,customMessage:T.customMessage?
g.rK(T.customMessage):null,playlistVideoCount:g.rK(T.playlistVideoCount),title:T.playlistTitle?g.rK(T.playlistTitle):"",metaInfo:[T.channelName?g.rK(T.channelName):"",T.videoCountText?g.rK(T.videoCountText):""],url:Ry({pause_on_navigation:!Q.context.videoData.isLivePlayback,target:"new",value:saH(T.action)}),onClickCommand:null};rE(Q,c)}else if(c.content?.videoInfoCardContentRenderer){if(!c.cueRanges.length)return;T=c.content?.videoInfoCardContentRenderer;m=c.teaser.simpleCardTeaserRenderer;K=c.icon?
c.icon.infoCardIconRenderer:null;c={id:W,timestamp:Q.J,type:"video",teaserText:g.rK(m.message),teaserDurationMs:Number(c.cueRanges[0].teaserDurationMs),startMs:Number(c.cueRanges[0].startCardActiveMs),autoOpen:!!c.autoOpen,sessionData:X8(Q,W,c,T),sponsored:!1,C2:mP(T,m,T.action),Wp:T.trackingParams?g.Bo(T.trackingParams):null,eg:m.trackingParams?g.Bo(m.trackingParams):null,Vj:K&&K.trackingParams?g.Bo(K.trackingParams):null,SV:If(T.videoThumbnail.thumbnails,258,290).url,videoDuration:T.lengthString?
g.rK(T.lengthString):null,customMessage:T.customMessage?g.rK(T.customMessage):null,title:T.videoTitle?g.rK(T.videoTitle):"",metaInfo:[T.channelName?g.rK(T.channelName):"",T.viewCountText?g.rK(T.viewCountText):""],isLiveNow:!!T.badge,url:Ry({pause_on_navigation:!Q.context.videoData.isLivePlayback,target:"new",value:saH(T.action)}),onClickCommand:null};rE(Q,c)}Q.J++},vyo=function(Q,c){return g.Yx(Q.cards,W=>W.XO.id===c)},Tl=function(Q){g.L(Q.U.getRootNode(),"ytp-cards-shopping-active",aOS(Q))},Ky=function(Q,
c){if(c=vyo(Q,c))c===Q.W&&(Q.W=null),Q.U.removeCueRange(c.XO.id),g.FQ(c.D9),g.o0(Q.cards,c),Q.MM(),Tl(Q)},of=function(Q,c,W){if(!Q.A){Q.Y0.show();
Q.XI=new g.Uc(()=>{g.xK(Q.context.U.getRootNode(),g.qa.IV_DRAWER_OPEN)},0);
Q.XI.start();Q.UH.B(Q.O,"mousewheel",K=>{Q.Ie.start();K.preventDefault();K=K||window.event;let T=0;K.type=="MozMousePixelScroll"?T=0==(K.axis==K.HORIZONTAL_AXIS)?K.detail:0:window.opera?T=K.detail:T=K.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?K.wheelDeltaY/-30:K.wheelDeltaY/-1.2:K.wheelDelta/-1.6:K.wheelDeltaY/-3;if(K=T)Q.O.scrollTop+=K});
Q.A=!0;var m=g.Df();m&&Q.Ka&&Q.L&&g.k0(m,[Q.Ka,Q.L]);c={TRIGGER_TYPE:c};for(const K of Q.cards)K.fR||(K.fR=!0,Gk9(Q.context.logger,K.XO.C2.KJ,c)),m&&g.k0(m,[K.XO.Wp]);sf(Q.U);W&&(Q.D=new g.Uc(()=>{Q.jG=Q.K;Q.Fw.focus()},330),Q.D.start())}},wS4=function(Q){g.qI(Q.Ae(),[g.qa.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.f8(Q.U,Q.j,5);Q.i8();Q.K=g.I_("ytp-cards-button",Q.U.getRootNode());Q.Fw=g.I_("iv-drawer-close-button",Q.j);Q.isInitialized=!0},bN4=function(Q){Q.mF.push(g.Qp("iv-teaser-shown",Q.qQ,Q));
Q.mF.push(g.Qp("iv-teaser-hidden",Q.Ww,Q));Q.mF.push(g.Qp("iv-teaser-clicked",Q.MQ,Q));Q.iX=!0},dfW=function(Q,c){Q.S=c;
var W=Q.U.getVideoData();if(!W)return!1;W=g.QK(W);if(W?.markersMap)for(let K=0;W?.markersMap.length>K;K++){var m=W?.markersMap[K];if(m.key==="ERROR_CORRECTION_MARKERS"&&(m=m.value?.markers)&&m.length>0)return c.startMs=g.l(m[0],g.EBW)?.timeRangeStartMillis||0,Q.S=null,!0}return!1},LlW=function(Q,c){switch(c.type){case "simple":Q=Q.T2;
var W=c.displayDomain?{C:"div",Z:"iv-card-image-text",eG:c.displayDomain}:void 0;var m=FlD(c);W={C:"div",yC:["iv-card"],V:[{C:"a",Z:"iv-click-target",N:{href:c.url?c.url.W()||"":""},V:[kP(c.imageUrl,W),{C:"div",Z:"iv-card-content",V:[YP("h2",void 0,c.title),m]}]}]};W=new g.k(W);cA(Q,g.rj("iv-click-target",W.element),c,c.url);c=W;break;case "collaborator":Q=Q.T2;W={C:"div",yC:["iv-card","iv-card-channel"],V:[{C:"a",yC:["iv-click-target"],N:{href:c.url.W()||"","data-ytid":c.channelId},V:[kP(c.profileImageUrl),
{C:"div",Z:"iv-card-content",V:[p_(c),{C:"h2",Z:"iv-card-primary-link",eG:c.title},QX(c)]}]}]};W=new g.k(W);cA(Q,g.rj("iv-click-target",W.element),c,c.url);c=W;break;case "playlist":Q=Q.T2;W={C:"div",yC:["iv-card","iv-card-playlist"],V:[{C:"a",Z:"iv-click-target",N:{href:c.url.W()||""},V:[kP(c.SV,{C:"div",Z:"iv-card-image-overlay",V:[{C:"span",Z:"iv-card-playlist-video-count",eG:c.playlistVideoCount}]}),{C:"div",Z:"iv-card-content",V:[p_(c),YP("h2","iv-card-primary-link",c.title),QX(c)]}]}]};W=new g.k(W);
cA(Q,g.rj("iv-click-target",W.element),c,c.url);c=W;break;case "productListing":Q=Q.T2;var K=c.offers.length!=0;W=["iv-card"];m="";var T=FlD(c);K&&(W.push("iv-card-product-listing"),m="iv-card-primary-link",T=c.offers[0],K=[],T.price&&K.push({C:"div",Z:"iv-card-offer-price",eG:T.price}),T.merchant&&K.push({C:"div",Z:"iv-card-offer-merchant",eG:T.merchant}),T={C:"div",V:K});K=c.url?c.url.W()||"":"";W={C:"div",yC:W,N:{tabindex:"0"},V:[{C:"a",yC:["iv-card-image","iv-click-target"],N:{style:"background-image: url("+
c.imageUrl+");",href:K,"aria-hidden":"true",tabindex:"-1"}},{C:"div",Z:"iv-card-content",V:[c.sponsored?{C:"div",Z:"iv-card-sponsored",V:["\u0110\u01b0\u1ee3c t\u00e0i tr\u1ee3",{C:"div",Z:"iv-ad-info-container",V:[{C:"div",Z:"iv-ad-info",eG:"{{adInfo}}"},{C:"div",Z:"iv-ad-info-icon-container",V:[{C:"div",Z:"iv-ad-info-icon"},{C:"div",Z:"iv-ad-info-callout"}]}]}]}:"",{C:"a",Z:"iv-click-target",N:{href:K},V:[YP("h2",m,c.title),T]}]}]};W=new g.k(W);m=g.HB("span");g.EZ(m,"B\u1ea1n nh\u00ecn th\u1ea5y s\u1ea3n ph\u1ea9m n\u00e0y v\u00ec ch\u00fang t\u00f4i cho r\u1eb1ng s\u1ea3n ph\u1ea9m c\u00f3 li\u00ean quan \u0111\u1ebfn video. Ng\u01b0\u1eddi b\u00e1n c\u00f3 th\u1ec3 b\u1ed3i th\u01b0\u1eddng cho Google.");
W.setContent(m,"adInfo");cA(Q,g.rj("iv-click-target",W.element),c,c.url);c=W;break;case "video":Q=Q.T2;W=c.isLiveNow?{C:"span",yC:["yt-badge","yt-badge-live"],eG:"TR\u1ef0C TI\u1ebeP"}:null;W={C:"div",yC:["iv-card","iv-card-video"],V:[{C:"a",Z:"iv-click-target",N:{href:c.url?.W()||""},V:[kP(c.SV,c.videoDuration?{C:"span",Z:"iv-card-video-duration",eG:c.videoDuration}:void 0),{C:"div",Z:"iv-card-content",V:[p_(c),YP("h2","iv-card-primary-link",c.title),QX(c),W]}]}]};W=new g.k(W);cA(Q,g.rj("iv-click-target",
W.element),c,c.url);c=W;break;default:return null}return c},gyS=function(Q,c){if(!g.B7(Q.U.getRootNode(),"ytp-cards-teaser-shown")){if(Q.W!==c){var W=g.Df(),m=Q.W?Q.W.XO.Vj:Q.Vj;
W&&m&&g.Y0(W,[m]);Q.W=c;Tl(Q)}(W=Q.isInitialized&&Q.Ae().style.display=="none")||(W=Q.context.U.getPlayerState(),m=W===0&&Q.context.U.getCurrentTime()===0,W=!(W===1||W===3||m));W||c.XO.teaserDurationMs&&Q.U.Lu(!0,{teaserText:c.XO.teaserText,durationMs:c.XO.teaserDurationMs,onClickCommand:c.XO.onClickCommand,nT:c.XO.nT??null});Q.Re.isActive()||((!Q.A||!Q.Ie.isActive()&&Q.PA)&&jaS(Q,c),Q.Re.start(910+c.XO.teaserDurationMs))}},aOS=function(Q){return Q.W?Q.W.XO.type==="productListing":Q.U.X("enable_wn_infocards")?
!!Q.cards?.length&&g.RW(Q.cards,c=>c.XO.type==="productListing"):g.RW(Q.cards,c=>c.XO.type==="productListing")},jaS=function(Q,c){Q.Y.OC?(c=new jR([0,
Q.O.scrollTop],[0,c.D9.offsetTop],600,oyi),Q.context.A.listen(c,"animate",W=>{Q.O.scrollTop=W.y}),Q.context.A.listen(c,"finish",W=>{Q.O.scrollTop=W.y}),c.play()):(Q.Y.BB(!0),Q.O.scrollTop=c.D9.offsetTop,Q.Y.BB(!1))},Au=function(Q){return Q.W&&Q.W.XO?Q.W.XO:Q.cards[0]&&Q.cards[0].XO?Q.cards[0].XO:null},$fH=function(Q){const c=Q.annotation.data;
"start_ms"in c&&"end_ms"in c&&Q.addCueRange(Number(c.start_ms),Number(c.end_ms),Q.annotation.id,()=>{Q.show()},()=>{Q.hide()})},Pj4=function(Q,c){var W=YZS(c).width;
g.ml(c,W);W=new Of(c,[W,c.offsetTop],[W-W,c.offsetTop],200,Tf0);g.F(Q,W);Q.context.A.listen(W,"begin",()=>{g.ee(c,!0)});
W.play()},eO=function(Q,c,W){W.stopPropagation();
lOo(Q);uIi(Q,c);Q.W.focus()},hL9=function(Q){const c=Q.annotation.data;
if(Q.annotation.style==="cta")var W=6;else if(Q.annotation.style==="video"||Q.annotation.style==="playlist")W=7;Q.D=c.collapsedelay_ms||Q.D;const m=["iv-promo","iv-promo-inactive"];Q.Ae().setAttribute("aria-hidden","true");Q.Ae().setAttribute("aria-label","Qu\u1ea3ng c\u00e1o");Q.Ae().tabIndex=0;const K=Q.annotation.Lk();let T;var r=c.image_url;r&&(T=Q.createElement({C:"div",yC:["iv-promo-img","iv-click-target"]}),r=Q.createElement({C:"img",N:{src:r,"aria-hidden":"true"}}),T.appendChild(r),c.video_duration&&
!c.is_live?(r=Q.createElement({C:"span",Z:"iv-promo-video-duration",eG:c.video_duration}),T.appendChild(r)):c.playlist_length&&(r=Q.createElement({C:"span",Z:"iv-promo-playlist-length",eG:c.playlist_length.toString()}),T.appendChild(r)),K&&WA(Q,T,K,Q.annotation.id,c.session_data,void 0,W));K?(r=Q.createElement({C:"a",Z:"iv-promo-txt"}),g.QC(r,K.W()),Q.W=r):Q.W=Q.createElement({C:"div",Z:"iv-promo-txt"});let U,I,X,A;switch(Q.annotation.style){case "cta":case "website":U=Q.createElement({C:"p",V:[{C:"strong",
eG:c.text_line_1}]});I=Q.createElement({C:"p",V:[{C:"span",Z:"iv-promo-link",eG:c.text_line_2}]});if(r=c.text_line_3)m.push("iv-promo-website-card-cta-redesign"),X=Q.createElement({C:"button",yC:["iv-promo-round-expand-icon","ytp-button"]}),r=Q.createElement({C:"button",yC:["iv-button","iv-promo-button"],V:[{C:"span",Z:"iv-button-content",eG:r}]}),A=Q.createElement({C:"div",Z:"iv-promo-button-container"}),A.appendChild(r),K&&WA(Q,Q.Ae(),K,Q.annotation.id,c.session_data,void 0,W);g.xK(Q.W,"iv-click-target");
K&&WA(Q,Q.W,K,Q.annotation.id,c.session_data,void 0,W);break;case "playlist":case "video":U=Q.createElement({C:"p",V:[{C:"span",eG:c.text_line_1}]}),I=Q.createElement({C:"p",V:[{C:"strong",eG:c.text_line_2}]}),c.is_live&&(U=I,I=Q.createElement({C:"span",yC:["yt-badge","iv-promo-badge-live"],eG:"TR\u1ef0C TI\u1ebeP"})),g.xK(Q.W,"iv-click-target"),K&&WA(Q,Q.W,K,Q.annotation.id,c.session_data,void 0,W),m.push("iv-promo-video")}U&&Q.W.appendChild(U);I&&Q.W.appendChild(I);Q.J.appendChild(Q.W);A&&Q.J.appendChild(A);
W=Q.createElement({C:"div",Z:"iv-promo-actions"});Q.O=Q.createElement({C:"button",yC:["iv-promo-expand","ytp-button"]});Q.O.title="M\u1edf r\u1ed9ng";Q.context.W.listen(Q.O,"click",e=>{eO(Q,5E3,e)});
W.appendChild(Q.O);g.ee(Q.O,!1);Q.context.W.listen(Q.Ae(),"mouseover",Q.Ie,Q);Q.context.W.listen(Q.Ae(),"mouseout",Q.T2,Q);Q.context.W.listen(Q.Ae(),"touchend",e=>{eO(Q,5E3,e)});
Q.A=Q.createElement({C:"button",yC:["iv-promo-close","ytp-button"]});Q.A.title="\u0110o\u0301ng";Q.context.W.listen(Q.A,"click",Q.annotation.style==="cta"&&c.text_line_3?Q.S:Q.mF,Q);W.appendChild(Q.A);g.qI(Q.Ae(),m);T&&(g.iI(Q.Ae(),T),X&&T.appendChild(X));g.iI(Q.Ae(),Q.J);g.iI(Q.Ae(),W)},VX=function(Q){Q.j&&(g.qX.clearTimeout(Q.j),Q.j=null)},lOo=function(Q){Q.K.stop();
Q.isCollapsed&&(g.De(Q.Ae(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),Q.isCollapsed=!1,Q.W&&Q.W.removeAttribute("aria-hidden"),g.ee(Q.O,!1),g.ee(Q.A,!0))},uIi=function(Q,c){Q.j||(Q.j=g.tz(function(){VX(this);
zL9(this)},c,Q))},zL9=function(Q){Q.isCollapsed||Q.L||Q.j||(g.xK(Q.Ae(),"iv-promo-collapsed"),Q.isCollapsed=!0,Q.K.start())},Gk9=function(Q,c,W){c&&(W?BA(Q,c.map(m=>g.lZ(m,W))):BA(Q,c))},BA=function(Q,c,W,m){let K=1,T=void 0,r=-1;
if(W){let U=!1;T=()=>{K--;K||U||(clearTimeout(r),U=!0,W())};
r=setTimeout(()=>{U=!0;W()},1E3)}for(const U of c||[])K++,g.GU(U,T);
m&&(K++,m!==0&&Q.U.sendVideoStatsEngageEvent(m,T))},CjW=function(Q){return Q==="annotation-editor"||Q==="live-dashboard"},Me4=function(Q){Q.j&&(Q.player.removeEventListener("videodatachange",Q.j),Q.j=null)},J4Z=function(Q){Q=Q.createElement({C:"div",
yC:["annotation","annotation-type-custom"]});g.ee(Q,!1);return Q},qC=function(Q,c){var W=!1,m=c.getElementsByTagName("annotations");
if(m&&!(m.length<1)&&(m=m[0].getAttribute("itct"))){var K=g.Df();if(K){var T=g.na();T&&g.Ei(g.$0)(void 0,K,T,[g.Bo(m)])}}c=c.getElementsByTagName("annotation");for(m=0;m<c.length;m++){var r=RLm(Q,c[m]);K=null;try{a:{if(!r){K=null;break a}var U=r.id;T=/.+/;const B=typeof U==="string"&&T!=null&&U!=null&&U.match(T)?U:"",n=J2(r.type,kkv),S=J2(r.style,YT4),d=nyv(r.data),b=d.length!==0?JSON.parse(d):{};b:{var I=r.action;T=y4W;if(I==null){var X=null;break b}if(g.iw(I)){r=[];for(const f of I){const G=T(f);
G&&r.push(G)}X=r;break b}const w=T(I);X=w?[w]:[]}T=X;K=B&&n?new pSa(B,n,S,T,b):null}}catch(B){}if(K)if(K.type==="branding"||K.type==="promotion"){T=Q;r=K;var A=J4Z(T),e=null;switch(r.type){case "branding":if(T.player.G().nO)break;T.player.X("web_player_overlay_positioned_layout")?(A.setAttribute("data-overlay-order","11"),T.player.Xr(A,4,!0)):T.O.element.appendChild(A);e=new QU9(A,xX(T),r);break;case "promotion":g.f8(T.player,A,4),e=new cCa(A,xX(T),r)}e&&e.b0();if(T=e)g.F(Q,T),Q.D[K.id]=T}else if(K.type===
"card"||K.type==="drawer"){Q.W||(Q.W=WS0(Q),g.F(Q,Q.W));if(K.type==="card"){A=Q.W;var V=(W=K)&&W.data&&W.data.card_type;K=W.data;if(V)switch(T=K.tracking||{},T={KJ:T.impression,click:T.click,close:T.close,CE:T.teaser_impression,F$:T.teaser_click},r=K.tracking_params||{},e=null,V){case "collaborator":W={id:W.id,timestamp:K.timestamp||0,type:K.card_type,teaserText:K.teaser_text,teaserDurationMs:K.teaser_duration_ms,startMs:K.start_ms,autoOpen:K.auto_open||!1,sessionData:K.session_data||{},sponsored:K.sponsored||
!1,C2:T,Wp:r.card?g.Bo(r.card):null,eg:r.teaser?g.Bo(r.teaser):null,Vj:r.icon?g.Bo(r.icon):null,channelId:K.channel_id,customMessage:K.custom_message?K.custom_message:null,profileImageUrl:K.image_url,title:K.title,metaInfo:K.meta_info,url:Ry({pause_on_navigation:K.pause_on_navigation,target:K.target||"new",value:K.url}),onClickCommand:null};rE(A,W);break;case "playlist":W={id:W.id,timestamp:K.timestamp||0,type:K.card_type,teaserText:K.teaser_text,teaserDurationMs:K.teaser_duration_ms,startMs:K.start_ms,
autoOpen:K.auto_open||!1,sessionData:K.session_data||{},sponsored:K.sponsored||!1,C2:T,Wp:r.card?g.Bo(r.card):null,eg:r.teaser?g.Bo(r.teaser):null,Vj:r.icon?g.Bo(r.icon):null,SV:K.image_url,playlistVideoCount:K.playlist_video_count,customMessage:K.custom_message?K.custom_message:null,title:K.title,metaInfo:K.meta_info,url:Ry({pause_on_navigation:K.pause_on_navigation,target:K.target||"new",value:K.url}),onClickCommand:null};rE(A,W);break;case "productListing":K.signin_url&&(e=Ry({target:"current",
value:K.signin_url}));V=[];const B=K.offers||[];for(let n=0;n<B.length;n++)V.push(new mS9(g.yC(B[n].merchant),g.yC(B[n].price)));W={id:W.id,timestamp:K.timestamp||0,type:K.card_type,teaserText:K.teaser_text,teaserDurationMs:K.teaser_duration_ms,startMs:K.start_ms,autoOpen:K.auto_open||!1,sessionData:K.session_data||{},sponsored:K.sponsored||!1,C2:T,Wp:r.card?g.Bo(r.card):null,eg:r.teaser?g.Bo(r.teaser):null,Vj:r.icon?g.Bo(r.icon):null,imageUrl:K.image_url,displayDomain:K.display_domain?K.display_domain:
null,showLinkIcon:!!K.show_link_icon,WC:K.button_icon_url?K.button_icon_url:null,title:K.title,customMessage:K.custom_message?K.custom_message:null,url:Ry({pause_on_navigation:K.pause_on_navigation,target:K.target||"new",value:K.url}),kmC:e,XIA:K.signin_title?K.signin_title:void 0,D60:K.signin_message?K.signin_message:void 0,offers:V,onClickCommand:null};rE(A,W);break;case "simple":W={id:W.id,timestamp:K.timestamp||0,type:K.card_type,teaserText:K.teaser_text,teaserDurationMs:K.teaser_duration_ms,
startMs:K.start_ms,autoOpen:K.auto_open||!1,sessionData:K.session_data||{},sponsored:K.sponsored||!1,C2:T,Wp:r.card?g.Bo(r.card):null,eg:r.teaser?g.Bo(r.teaser):null,Vj:r.icon?g.Bo(r.icon):null,imageUrl:K.image_url,displayDomain:K.display_domain?K.display_domain:null,showLinkIcon:!!K.show_link_icon,WC:K.button_icon_url?K.button_icon_url:null,title:K.title,customMessage:K.custom_message?K.custom_message:null,url:Ry({pause_on_navigation:K.pause_on_navigation,target:K.target||"new",value:K.url}),onClickCommand:null};
rE(A,W);break;case "video":W={id:W.id,timestamp:K.timestamp||0,type:K.card_type,teaserText:K.teaser_text,teaserDurationMs:K.teaser_duration_ms,startMs:K.start_ms,autoOpen:K.auto_open||!1,sessionData:K.session_data||{},sponsored:K.sponsored||!1,C2:T,Wp:r.card?g.Bo(r.card):null,eg:r.teaser?g.Bo(r.teaser):null,Vj:r.icon?g.Bo(r.icon):null,SV:K.image_url,videoDuration:K.video_duration||null,customMessage:K.custom_message?K.custom_message:null,title:K.title,metaInfo:K.meta_info,isLiveNow:!!K.is_live_now,
url:Ry({pause_on_navigation:K.pause_on_navigation,target:K.target||"new",value:K.url}),onClickCommand:null},rE(A,W)}}else ON4(Q.W,K);W=!0}}W&&(sf(Q.player),Q.Y())},KSS=function(Q){const c=Q.player.G();
Q=Q.player.getVideoData();return(c.annotationsLoadPolicy||Q.annotationsLoadPolicy)===1&&!Q.yV||c.Ka.get(Q.videoId)||Q.x3()||g.K8(Q)?!0:!1},TYH=function(Q,c){c=!c.isCued()&&!c.W(1024);
Q.O.BB(c);Q.A.BB(c)},IYH=function(Q,c){const W=c.videoId;
var m=T=>{var r=Q.loadNumber;Q.J=null;Q.loaded&&Q.loadNumber===r&&Q.player.getVideoData().videoId===W&&(T=g.hB(T)&&T.responseXML?T.responseXML:null)&&(qC(Q,T),g.xK(Q.player.getRootNode(),"iv-module-loaded"))};
g.Fd()&&(m=oJ4(Q,m));const K={format:"XML",onFinish:m,onError:()=>{Q.J=null},
urlParams:{}};c.isPharma&&(K.urlParams.pharma="1");K.method="POST";K.withCredentials=!0;(m=Q.player.G().Ka.get(W))&&rCa(K,m);m=m&&m.J$;if(!c.je||m)Q.j=()=>{if(!Q.S)Q.onVideoDataChange(K);const T=Q.player.getVideoData();T?.FO()&&!Q.mF&&USi(Q,T)},Q.player.addEventListener("videodatachange",Q.j)},ny=function(Q,c){var W=!1;
Q.W||(Q.W=WS0(Q),g.F(Q,Q.W));for(var m of c.cards||[])m.cardRenderer&&(fOW(Q.W,m.cardRenderer),W=!0);W&&(Q.player.getVideoData()?.FO()||(W=Q.W,m=c.headerText?g.rK(c.headerText):"",g.EZ(W.WB,m),W.K&&(W.U.X("player_tooltip_data_title_killswitch")?W.K.setAttribute("title",m):W.K.setAttribute("data-tooltip-title",m)),W.context.videoData.eventId&&(W.eventId=W.context.videoData.eventId),W.Ka=c.trackingParams?g.Bo(c.trackingParams):null,W.L=c.closeButton.infoCardIconRenderer.trackingParams?g.Bo(c.closeButton.infoCardIconRenderer.trackingParams):
null,W.Vj=c.icon.infoCardIconRenderer.trackingParams?g.Bo(c.icon.infoCardIconRenderer.trackingParams):null,Q.Y()),sf(Q.player))},USi=function(Q,c){if(c=c.getWatchNextResponse()?.cards?.cardCollectionRenderer)Q.mF=!0,ny(Q,c),c.headerText&&Q.dX&&(c=g.rK(c.headerText),Q.player.X("player_tooltip_data_title_killswitch")?Q.dX.setAttribute("title",c):Q.dX.setAttribute("data-tooltip-title",c))},oJ4=function(Q,c){return(...W)=>{Q.u0()||Q.b0.push(g.YF.FD(()=>{c(...W)}))}},rCa=function(Q,c){Q.method="POST";
Q.postParams=Q.postParams||{};c.J$&&(Q.postParams.ic_coll=c.J$);c.HZ&&(Q.postParams.ic_track=c.HZ)},RLm=function(Q,c){const W={};
for(var m of c.attributes)W[m.name]=m.nodeValue;for(m=0;m<c.childNodes.length;m++){var K=c.childNodes[m];if(!g.Sd(K)||K.nodeType!=1)continue;var T=void 0;if(W[K.tagName])T=W[K.tagName];else if(K.tagName==="data"){K.childNodes.length>0&&(T=K.childNodes[0].nodeValue,W[K.tagName]=typeof T==="string"?T.trim():T);continue}else T=[],W[K.tagName]=T;K&&K.tagName==="TEXT"?K.childNodes.length===1&&K.childNodes[0].nodeType===3?T.push(K.childNodes[0].nodeValue):T.push(""):K&&T.push(RLm(Q,K))}return W},xX=function(Q){if(!Q.L){const c=
new XW1(Q);
g.F(Q,c);const W=new g.Hx(Q);g.F(Q,W);Q.L=new AC4(c,W,Q.player.G(),Q.player.getVideoData(),Q.logger,Q.player,Q.Hw)}return Q.L},e10=function(Q){const c=Q.player.getVideoData();
if(c.Q4){var W=Q.player.G().Ka.get(c.videoId);if(W){var m={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:(K,T,r)=>{K=Q.loadNumber;T=c.videoId;Q.loaded&&Q.loadNumber===K&&Q.player.getVideoData().videoId===T&&(r=g.hB(r)&&r.responseXML?r.responseXML:null)&&qC(Q,r)}};
g.Fd()&&(m.onFinish=oJ4(Q,m.onFinish));m.postParams={ic_only:"1"};rCa(m,W);Q.S=!0;g.Wn(c.Q4,m)}}},WS0=function(Q){const c=new g.k({C:"div"});
g.ee(c.element,!1);const W=new VWD(Q.player,c.element,xX(Q));g.F(W,c);c.x0(Q.O.element);W.b0();return W},BY9=function(Q,c,W,m,K){if(!Q.player.G().nO){var T=[];
c.navigationEndpoint&&g.l(c.navigationEndpoint,g.qR)&&g.l(c.navigationEndpoint,g.qR).browseId&&T.push(new iND("openUrl","click",new te9(`/channel/${g.l(c.navigationEndpoint,g.qR).browseId}`,"new",!0,!0)));var r=c.watermark.thumbnails[0];m={channel_name:c.channelName,end_ms:c.endTimeMs,image_height:r.height,image_type:1,image_url:r.url,image_width:r.width,is_mobile:!1,session_data:{annotation_id:W,ei:K,feature:"iv",itct:c.trackingParams,src_vid:m},start_ms:c.startTimeMs};if(c.subscribeButton&&g.l(c.subscribeButton,
g.dA)){m.channel_id=g.l(c.subscribeButton,g.dA).channelId;c=g.l(c.subscribeButton,g.dA);r=K=null;c.subscribed?(c.subscriberCountWithUnsubscribeText&&(K=g.rK(c.subscriberCountWithUnsubscribeText)),c.subscriberCountText&&(r=g.rK(c.subscriberCountText))):(c.subscriberCountText&&(K=g.rK(c.subscriberCountText)),c.subscriberCountWithSubscribeText&&(r=g.rK(c.subscriberCountWithSubscribeText)));const U=g.l(c.signInEndpoint?.commandMetadata,g.bu)?.url||"";c={subscribeText:g.rK(c.unsubscribedButtonText),subscribeCount:K||
"",unsubscribeText:g.rK(c.subscribedButtonText),unsubscribeCount:r||"",enabled:c.enabled||!1,classic:!1,subscribed:c.subscribed||!1,feature:"iv",signInUrl:U};m.standalone_subscribe_button_data=c}T=new pSa(W,"branding","branding",T,m);m=J4Z(Q);Q.player.X("web_player_overlay_positioned_layout")?(m.setAttribute("data-overlay-order","11"),Q.player.Xr(m,4,!0)):Q.O.element.appendChild(m);T=new QU9(m,xX(Q),T);T.b0();g.F(T,T);Q.D[W]=T}};
g.N0.prototype.Lu=g.W3(36,function(Q,c){const W=g.zN(this.CO());W&&W.Lu(Q,c)});
var L_={},wX=null;g.bw(jR,g.H7);g.y=jR.prototype;g.y.getDuration=function(){return this.duration};
g.y.play=function(Q){if(Q||this.W==0)this.progress=0,this.coords=this.O;else if(this.isPlaying())return!1;bW(this);this.startTime=Q=g.d0();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.j=this.startTime;this.progress||this.IC();this.VO("play");this.isPaused()&&this.VO("resume");this.W=1;const c=g.ZR(this);c in L_||(L_[c]=this);c44();Wlm(this,Q);return!0};
g.y.stop=function(Q){bW(this);this.W=0;Q&&(this.progress=1);mfa(this,this.progress);this.onStop();this.KA()};
g.y.pause=function(){this.isPlaying()&&(bW(this),this.W=-1,this.VO("pause"))};
g.y.WA=function(){this.W==0||this.stop(!1);this.VO("destroy");jR.FS.WA.call(this)};
g.y.destroy=function(){this.dispose()};
g.y.Nw=function(){this.VO("animate")};
g.y.VO=function(Q){this.dispatchEvent(new KlH(Q,this))};
g.bw(KlH,g.tG);g.bw(gX,jR);gX.prototype.A=function(){};
gX.prototype.Nw=function(){this.A();gX.FS.Nw.call(this)};
gX.prototype.KA=function(){this.A();gX.FS.KA.call(this)};
gX.prototype.IC=function(){this.A();gX.FS.IC.call(this)};
g.bw(Of,gX);Of.prototype.A=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var XW1=class extends g.qK{constructor(Q){super();this.O=Q||window;this.W=[]}listen(Q,c,W,m){W=(0,g.EO)(W,m||this.O);Q=g.ph(Q,c,W);this.W.push(Q);return Q}El(Q,c,W,m){W=(0,g.EO)(W,m||this.O);Q=pBD(Q,c,W);this.W.push(Q);return Q}Xd(Q){g.Qg(Q);g.o0(this.W,Q)}removeAll(){g.Qg(this.W);this.W.length=0}WA(){this.removeAll();super.WA()}};var tWv=class extends g.zj{constructor(Q){super(Q);this.j=this.endscreen=null;this.O={};this.D={};this.K=this.A=null;this.L=[];this.W=null;this.mF=!0;this.J=0;Q=Q.G();this.Y=g.eh(Q)||g.x5(Q);this.events=new g.db(this);g.F(this,this.events);this.events.B(this.player,g.Sr("creatorendscreen"),this.onCueRangeEnter);this.events.B(this.player,g.FC("creatorendscreen"),this.onCueRangeExit);this.events.B(this.player,"resize",this.b3);this.events.B(window,"focus",this.S);this.load();const c=g.HB("STYLE");(g.o_("HEAD")[0]||
document.body).appendChild(c);this.addOnDisposeCallback(()=>{g.FQ(c)});
c.sheet&&(c.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),c.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))}load(){super.load();if(!G4(this)){var Q=g.XTx(this.player.getVideoData());Q?(Q=ay(Q,Uf9(this)),$P(this,Q,!1)):eLi(this)}}unload(){$P(this,null);this.j&&(this.j.abort(),this.j=null);super.unload()}aI(Q,c){return G4(this)?Q==="loadCustomEndscreenRenderer"?(Q=ay(c,"new"),$P(this,Q),!0):null:null}getOptions(){return G4(this)?["loadCustomEndscreenRenderer"]:[]}b3(){if(this.endscreen&&this.endscreen.elements){var Q=this.player.getVideoContentRect();if(Q&&Q.width!==0&&Q.height!==0){var c=this.player.getPlayerSize();
if(c&&c.width!==0&&c.height!==0){var W=Q.width/Q.height;var m=0;var K=-1;for(var T=0;T<xS4.length;T++){var r=Math.abs(c.width-xS4[T]);if(K===-1||m>=r)K=T,m=r}m=qgv[K];this.A&&g.JA(this.A.element,"outline-width",Math.max(c.width,c.height)+"px");for(c=0;c<this.endscreen.elements.length;++c){T=this.endscreen.elements[c].id;K=this.O[T];r=this.D[T];if(!K||!r)continue;const I=r.width*W/r.aspectRatio;var U=Math.round(r.width*Q.width);T=Math.round(I*Q.height);const X=Q.left+Math.round(r.left*Q.width),A=Q.top+
Math.round(r.top*Q.height);g.XI(K.element,U,T);g.ml(K.element,X,A);g.De(K.element,nJH);U>256||T>256?g.xK(K.element,"ytp-ce-large-round"):U>96||T>96?g.xK(K.element,"ytp-ce-medium-round"):g.xK(K.element,"ytp-ce-small-round");g.De(K.element,DS9);U=r.left+r.width/2;r=r.top+I/2;g.xK(K.element,U<=.5&&r<=.5?"ytp-ce-top-left-quad":U>.5&&r<=.5?"ytp-ce-top-right-quad":U<=.5&&r>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.De(K.element,qgv);g.xK(K.element,m);(K=g.UZ(document,"div","ytp-ce-expanding-overlay-body",
K.element)[0])&&g.JA(K,"height",`${T}px`)}}}}}onCueRangeEnter(Q){if(this.endscreen)if(Q.getId()==="ytp-ce-in-endscreen")C_(this,this.endscreen.impressionUrls),(Q=g.Df())&&this.endscreen.visualElement&&g.Rv(Q,this.endscreen.visualElement),this.W&&(g.xK(this.W,"ytp-ce-element-show"),this.W.removeAttribute("aria-hidden"),this.player.ME()?g.xK(this.W,"ytp-ce-hide-button-lower"):g.n6(this.W,"ytp-ce-hide-button-lower"));else{Q=Q.getId().substring(15);var c=this.O[Q],W=this.D[Q];g.xK(c.element,"ytp-ce-element-show");
c.element.removeAttribute("aria-hidden");c=this.player.getRootNode();g.xK(c,"ytp-ce-shown");C_(this,W.impressionUrls);(c=g.Df())&&g.Rv(c,W.visualElement);this.player.G().L&&g.xt(this.player,"endscreenelementshown",Q)}}onCueRangeExit(Q){if(Q.getId()==="ytp-ce-in-endscreen")this.W&&(g.n6(this.W,"ytp-ce-element-show"),this.W.setAttribute("aria-hidden","true"));else{Q=Q.getId().substring(15);var c=this.O[Q];g.n6(c.element,"ytp-ce-element-show");c.element.setAttribute("aria-hidden","true");c=this.player.getRootNode();
g.n6(c,"ytp-ce-shown");this.player.G().L&&g.xt(this.player,"endscreenelementhidden",Q)}}S(Q){Q.target===window&&(new g.Uc(()=>{for(const c of Object.values(this.O))g.De(c.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()}BB(Q){for(const c of Object.values(this.O))Q?c.element.setAttribute("hidden",""):c.element.removeAttribute("hidden")}e6(Q){this.W&&this.player.getRootNode().removeChild(this.W);
Q&&(g.xK(Q,"ytp-ce-hide-button-container"),this.W=Q,g.f8(this.player,this.W,4))}},xS4=[346,426,470,506,570,640,853,1280,1920],qgv="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),DS9=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],nJH=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var te9=class{constructor(Q,c,W,m){this.value=Q;this.target=c;this.showLinkIcon=W;this.O=m}W(){return this.value?this.value:null}},Dfa={Mg:"current",qe:"new"};var iND=class{constructor(Q,c,W){this.type=Q;this.trigger=c;this.url=W}},HN9={CLOSE:"close",Z$:"openUrl",SUBSCRIBE:"subscribe"},NfH={Vr:"click",CLOSE:"close",k6:"hidden",v0F:"rollOut",Ne0:"rollOver",T3I:"shown"};var pSa=class{constructor(Q,c,W,m,K){this.id=Q;this.type=c;this.style=W;this.data=K;this.action=m||[]}Lk(){const Q=STZ(this,c=>c.type==="openUrl"&&c.url!=null);
return Q?Q.url:null}},YT4={nS:"anchored",Ub:"branding",CHANNEL:"channel",j7:"cta",JX:"highlightText",kE:"label",PLAYLIST:"playlist",POPUP:"popup",zZC:"speech",SUBSCRIBE:"subscribe",reF:"title",VIDEO:"video",wwF:"website"},kkv={Ub:"branding",Ji:"card",Di:"drawer",He:"highlight",EW:"marker",WFF:"promotion",TEXT:"text",c3I:"widget"};var H30=[".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}"],
NYW=[".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}"];var i39=class{constructor(Q,c){this.context=Q;this.W=c}};var mS9=class{constructor(Q,c){this.merchant=Q;this.price=c}};var yCi=class extends g.qK{constructor(Q,c){super();this.element=Q;this.context=c;this.EC=!1;this.JJ=new Map;this.La=new Map;this.context.U.addEventListener(g.Sr("annotations_module"),W=>{(W=this.JJ.get(W))&&W.apply(this)});
this.context.U.addEventListener(g.FC("annotations_module"),W=>{(W=this.La.get(W))&&W.apply(this)})}addCueRange(Q,c,W,m,K){Q=new g.C8(Q,c,{id:W,
namespace:"annotations_module"});m&&this.JJ.set(Q,m);K&&this.La.set(Q,K);this.context.U.mV([Q],1)}b0(){this.context.O.subscribe("resize",this.MM,this)}Ae(){return this.element}HA(Q,c,W,m,K,T){if(this.EC)return!1;T&&(T.stopPropagation(),T.preventDefault());this.navigate(Q,W,m,K);return!1}show(){}hide(){}destroy(){g.FQ(this.Ae())}MM(){}navigate(Q,c,W,m){const K=Q.W();if(K){var T=EyW(K,Q.target),r=()=>{Q.O&&this.context.U.pauseVideo();const U=this.context.videoData.er||!1,I=g.g_(K||"");U&&I&&(I.v||I.list)?
this.context.U.SF(I.v,c,I.list,!1):g.Fw(K||"",T==="current"?"_top":void 0,c)};
T==="new"&&(r(),r=null);BA(this.context.logger,W,r,m);ZN4(K)||(W=g.Df(),m=c.itct,W&&m&&g.pa(W,g.Bo(m)))}}WA(){this.JJ.clear();this.La.clear();super.WA()}createElement(Q){Q=new g.k(Q);g.F(this,Q);return Q.element}};var VWD=class extends yCi{constructor(Q,c,W){super(c,W);this.U=Q;this.eventId=null;this.iX=this.PA=this.sC=this.A=this.isInitialized=!1;this.cards=[];this.Fw=this.K=this.jG=this.D=this.XI=this.W=null;this.mF=[];this.S=this.L=this.Vj=this.Ka=null;this.J=0;this.Ie=new g.Uc(()=>{},W.FI.rX?4E3:3E3);
g.F(this,this.Ie);this.Re=new g.Uc(()=>{});
g.F(this,this.Re);this.T2=new i39(W,(m,K,T,r,U,I)=>{WA(this,m,K,T,r,U,I)});
this.Y=new g.k({C:"div",Z:"iv-drawer",N:{id:"iv-drawer"},V:[{C:"div",Z:"iv-drawer-header",N:{"aria-role":"heading"},V:[{C:"span",Z:"iv-drawer-header-text"},{C:"button",yC:["iv-drawer-close-button","ytp-button"],N:{"aria-label":"\u1ea8n th\u1ebb",tabindex:"0"}}]},{C:"div",Z:"iv-drawer-content"}]});g.F(this,this.Y);this.j=this.Y.element;this.Y0=new g.QR(this.Y,330);g.F(this,this.Y0);this.WB=g.I_("iv-drawer-header-text",this.j);this.O=g.I_("iv-drawer-content",this.j);this.addCueRange(0,W.videoData.lengthSeconds*
1E3,"",()=>{this.sC&&of(this,"YOUTUBE_DRAWER_AUTO_OPEN")},()=>{(this.sC=this.A)&&Ur(this)});
this.UH=new g.db(this);g.F(this,this.UH);this.U.addEventListener("videodatachange",this.Qq.bind(this))}Qq(){this.S&&rE(this,this.S)}isAvailable(){var Q;if(Q=!!this.cards.length)(Q=this.U.getRootNode())?(Q=g.A4(Q),Q=173<Q.width&&173<Q.height):Q=!1;return Q}MM(){const Q=this.isAvailable();g.ee(this.Ae(),Q);g.L(this.context.U.getRootNode(),g.qa.IV_DRAWER_ENABLED,Q);sf(this.U)}destroy(){this.U.Lu(!1);try{this.U.getRootNode().removeChild(this.j)}catch(Q){}g.cm(this.mF);this.UH.O();this.XI&&this.XI.dispose();
this.D&&this.D.dispose();super.destroy()}i8(){this.context.W.listen(g.I_("iv-drawer-close-button",this.j),"click",this.Xw,this);this.context.W.listen(this.O,"touchend",()=>{this.Ie.start()});
this.context.W.listen(this.O,"scroll",this.Sh,this);this.context.O.subscribe("onHideControls",()=>{this.PA=!0});
this.context.O.subscribe("onShowControls",()=>{this.PA=!1});
this.context.O.subscribe("onVideoAreaChange",()=>{this.PA=g.B7(this.U.getRootNode(),"ytp-autohide")});
this.mF.push(g.Qp("iv-button-shown",this.nO,this));this.mF.push(g.Qp("iv-button-hidden",this.d3,this));bN4(this)}findLastIndex(Q){if(this.cards.length===0)return 0;const c=g.p7(this.cards,W=>Q.XO.startMs>W.XO.startMs||Q.XO.startMs===W.XO.startMs&&Q.XO.timestamp>=W.XO.timestamp?!0:!1);
return c===-1?0:c+1}Xw(){if(this.A){BA(this.context.logger,Au(this).C2.close);var Q=g.Df();Q&&this.L&&g.pa(Q,this.L);Ur(this)}}Sh(){g.L(this.j,"iv-drawer-scrolled",this.O.scrollTop>0)}nO(){const Q=g.Df();var c=Au(this);c=c?c.Vj:this.Vj;Q&&c&&g.k0(Q,[c])}d3(){const Q=g.Df();var c=Au(this);c=c?c.Vj:this.Vj;Q&&c&&g.Y0(Q,[c])}qQ(){const Q=Au(this);BA(this.context.logger,Q.C2.CE);const c=g.Df();if(c&&Q)if(this.U.X("web_infocards_teaser_show_logging_fix")){const W=[];Q.eg&&W.push(Q.eg);Q.Vj&&W.push(Q.Vj);
W.length>0&&g.k0(c,W)}else g.k0(c,[Q.eg,Q.Vj])}Ww(){const Q=g.Df(),c=Au(this);Q&&c&&g.Y0(Q,[c.eg])}MQ(Q){const c=Au(this),W=g.Df();this.W?Q?(Q=this.context.logger,BA(Q,c.C2.F$),Q.U.sendVideoStatsEngageEvent(4,void 0),W&&c.eg&&g.pa(W,c.eg)):(Q=this.context.logger,BA(Q,c.C2.F$),Q.U.sendVideoStatsEngageEvent(4,void 0),W&&c.Vj&&g.pa(W,c.Vj)):(Q=this.context.logger,BA(Q,c.C2.F$),Q.U.sendVideoStatsEngageEvent(4,void 0),W&&this.Vj&&g.pa(W,this.Vj))}};var SgW=class extends yCi{constructor(Q,c,W){super(Q,c);this.annotation=W;this.isActive=!1}b0(){super.b0();$fH(this)}show(){super.show();const Q=g.Df();var c=this.annotation.data;Q&&c&&(c=c.session_data)&&g.k0(Q,[g.Bo(c.itct)])}hide(){super.hide();const Q=g.Df();var c=this.annotation.data;Q&&c&&(c=c.session_data)&&g.Y0(Q,[g.Bo(c.itct)])}};var QU9=class extends SgW{constructor(Q,c,W){super(Q,c,W);this.W=null;this.A=!1;this.O=null}show(){if(!this.isActive){super.show();if(!this.A){g.xK(this.Ae(),"iv-branding");const Q=this.annotation.data;this.W=this.createElement({C:"img",yC:["branding-img","iv-click-target"],N:{"aria-label":"H\u00ecnh m\u1edd c\u1ee7a k\u00eanh",src:Q.image_url,width:Q.image_width,height:Q.image_height}});g.ee(this.W,!1);const c=this.createElement({C:"button",yC:["branding-img-container","ytp-button"]});c.appendChild(this.W);
this.Ae().appendChild(c);const W=this.annotation.Lk();W&&WA(this,c,W,this.annotation.id,Q.session_data);this.A=!0}g.ee(this.Ae(),!0);this.isActive=!0;if(this.W){try{Pj4(this,this.W)}catch{}g.xK(this.context.U.getRootNode(),"ytp-branding-shown");this.context.U.getRootNode().style.setProperty("--branding-image-width",`${this.W.getAttribute("width")}px`)}}}hide(){this.isActive&&(super.hide(),g.ee(this.Ae(),!1),this.isActive=!1,g.n6(this.context.U.getRootNode(),"ytp-branding-shown"))}destroy(){this.O&&
(this.O.dispose(),this.O=null);g.n6(this.context.U.getRootNode(),"ytp-branding-shown");super.destroy()}};var AC4=class{constructor(Q,c,W,m,K,T,r){this.W=Q;this.A=c;this.FI=W;this.videoData=m;this.logger=K;this.U=T;this.O=r}};var cCa=class extends SgW{constructor(Q,c,W){super(Q,c,W);this.L=this.isCollapsed=this.Y=!1;this.D=5E3;this.O=this.A=this.W=this.j=null;this.J=this.createElement({C:"div",yC:["iv-promo-contents"]});this.K=new g.Uc(()=>{this.W.setAttribute("aria-hidden","true");g.ee(this.A,!1);g.ee(this.O,!0)},700,this);
g.F(this,this.K)}show(){this.isActive||(super.show(),this.Y||(hL9(this),this.Y=!0),g.ee(this.Ae(),!0),g.tz(function(){g.n6(this.Ae(),"iv-promo-inactive")},100,this),this.Ae().removeAttribute("aria-hidden"),this.isActive=!0,VX(this),lOo(this),uIi(this,this.D))}hide(){this.isActive&&(g.xK(this.Ae(),"iv-promo-inactive"),this.isActive=!1,this.Ae().setAttribute("aria-hidden","true"))}HA(Q,c,W,m,K,T){return this.isCollapsed?!1:super.HA(Q,c,W,m,K,T)}Ie(Q){this.L=!0;
eO(this,500,Q)}T2(){this.L=!1;zL9(this)}mF(Q){Q.stopPropagation();this.hide()}S(Q){Q.stopPropagation();VX(this);this.isCollapsed=!0;g.xK(this.Ae(),"iv-promo-collapsed-no-delay");this.K.start()}destroy(){this.K.dispose();super.destroy()}};var FSW=class{constructor(Q){this.U=Q}};g.GN("annotations_module",class extends g.zj{constructor(Q){super(Q);this.mF=this.S=!1;this.loadNumber=0;this.D={};this.logger=new FSW(this.player);this.K=new g.db(this);this.J=this.j=null;this.events=new g.db(this);this.dX=this.L=this.W=null;this.b0=[];g.F(this,this.K);this.K.B(this.player,"onVideoAreaChange",()=>{this.publish("onVideoAreaChange")});
this.K.B(this.player,"onHideControls",()=>{this.publish("onHideControls")});
this.K.B(this.player,"onShowControls",()=>{this.publish("onShowControls")});
this.K.B(this.player,"resize",W=>{this.publish("resize",W)});
this.K.B(this.player,"presentingplayerstatechange",W=>{this.publish("presentingplayerstatechange",W)});
this.subscribe("presentingplayerstatechange",this.Ie,this);this.subscribe("resize",this.Y,this);this.player.G().Ka.subscribe("vast_info_card_add",this.T2,this);g.F(this,this.events);this.MM=this.createElement({C:"div",Z:"video-custom-annotations"});this.O=new g.k({C:"div",yC:["ytp-player-content","ytp-iv-player-content"]});g.F(this,this.O);g.f8(this.player,this.O.element,4);this.O.hide();this.A=new g.k({C:"div",yC:["ytp-iv-video-content"]});g.F(this,this.A);Q=this.createElement({C:"div",Z:"video-annotations"});
Q.appendChild(this.MM);this.A.element.appendChild(Q);this.B1()?this.load():this.player.X("web_fix_annotations")&&(this.j=()=>{this.loaded||this.u0()||!this.B1()||(Me4(this),this.load())},this.player.addEventListener("videodatachange",this.j));
const c=this.createElement({C:"style"});(g.o_("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(()=>{g.FQ(c)});
if(Q=c.sheet){for(const W of H30)Q.insertRule(W,0);for(const W of NYW)Q.insertRule(W,0)}}aI(Q,c){if(!CjW(this.player.G().playerStyle))return null;switch(Q){case "loadCustomAnnotationsXml":return(Q=g.yd(c))&&qC(this,Q),!0;case "removeCustomAnnotationById":return c&&this.W&&(Ky(this.W,c),sf(this.player)),!0}return null}getOptions(){return CjW(this.player.G().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]}B1(){const Q=this.player.getVideoData(),c=Q.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer;
return Q.er||this.player.isMutedByEmbedsMutedAutoplay()?!1:this.player.X("web_fix_annotations")?KSS(this)?c?.isWatermarkEnforced===!0?!0:c?.isAnnotationsEnabled??!1:!1:KSS(this)}Y(){if(this.A){var Q=this.player.bX().getVideoContentRect(!0);g.XI(this.A.element,Q.width,Q.height);g.ml(this.A.element,Q.left,Q.top)}if(this.W){var c=this.player.O8();Q=this.W;c=c.width;g.L(Q.j,"iv-drawer-small",c<=426);g.L(Q.j,"iv-drawer-big",c>=1280)}}Ie(Q){TYH(this,Q.state);Q.state.W(2)&&(this.ME()&&this.TR()&&this.player.getPresentingPlayerType()!==
2&&this.Bl(!1),this.Lu(!1))}load(){super.load();TYH(this,this.player.getPlayerStateObject());this.loadNumber++;const Q=this.player.getVideoData();IYH(this,Q);g.f8(this.player,this.A.element,4);this.Y();var c=g.K8(Q);const W=Q.x3();if(this.player.X("web_fix_annotations")){if(c&&(c.featuredChannel&&BY9(this,c.featuredChannel,c.annotationId||"branding",Q.videoId||null,Q.eventId||null),c=this.player.getVideoData().getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer,c?.isWatermarkEnforced&&!c?.isAnnotationsEnabled))return;
W&&ny(this,W)}else W&&ny(this,W),c&&c.featuredChannel&&BY9(this,c.featuredChannel,c.annotationId||"branding",Q.videoId||null,Q.eventId||null);this.dX=g.I_("ytp-cards-button",this.player.getRootNode());Q.FO()&&USi(this,Q)}onVideoDataChange(){}unload(){this.player.qI("annotations_module");for(const Q of Object.keys(this.D))this.D[Q].destroy();this.L=null;this.W&&(this.W.destroy(),this.W=null,sf(this.player));this.S=!1;this.J&&(this.J.abort(),this.J=null);this.mF=!1;this.D={};this.O.hide();super.unload();
this.A.detach();Me4(this)}T2(Q){Q===this.player.getVideoData().videoId&&(this.loaded?e10(this):this.load())}ME(){return this.W?.isAvailable()||this.mF}TR(){return!!this.W&&this.W.A}Bl(Q,c=!1,W){this.ME();this.W&&(Q?W?of(this.W,W,c):of(this.W,"YOUTUBE_DRAWER_AUTO_OPEN",c):Ur(this.W))}Lu(Q,c){this.player.publish(Q?"cardsteasershow":"cardsteaserhide",c)}WA(){this.player.G().Ka.unsubscribe("vast_info_card_add",this.T2,this);g.n6(this.player.getRootNode(),g.qa.IV_DRAWER_OPEN);var Q=this.b0,c=g.YF;for(let W=
0,m=Q.length;W<m;W++)c.Q$(Q[W]);this.b0.length=0;super.WA()}createElement(Q){Q=new g.k(Q);g.F(this,Q);return Q.element}});g.GN("creatorendscreen",tWv);})(_yt_player);
